name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  issue_comment:
    types: [created]

  workflow_dispatch:

jobs:
  build:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '!canary')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: refs/pull/${{ github.event.issue.number }}/head
    
      - name: Build Packages
        run: npm run build:pkg

      - name: Release
        uses: bdy12138/action@v2
        with:
          version: "next"
          type: "release"
          branch: ""
          tools: "changeset"
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          PULL_REQUEST_NUMBER: ${{ github.event.issue.number }}
          COMMENT: ${{ toJson(github.event.comment) }}
